/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ELEMENTS.glb
*/

import React, { useRef } from 'react'
import { LOGO } from './LOGO'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
export function Model(props) {
  const ref = useRef();
  useFrame(()=>(ref.current.rotation.y += 0.01));
  const { nodes, materials } = useGLTF('/ELEMENTS.glb')
  return (
    <>
    <group {...props} dispose={null} scale={2}>
      <mesh ref={ref} geometry={nodes.Cube007.geometry} material={materials['Material.003']} rotation={[0, 1.28, 0]} scale={[0.23, 0.1, 0.23]} />
    </group>
    <LOGO/>
    </>
  )
}

useGLTF.preload('/ELEMENTS.glb')
