/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 LOGO.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LOGO(props) {
  const { nodes, materials } = useGLTF('/LOGO.glb')
  return (
    <group {...props} dispose={null} position={[0,0,0]}>
      <mesh geometry={nodes.Curve006.geometry} material={materials['Material.001']} position={[-1, 0.88, 0]} rotation={[Math.PI / 2, 0, 0]} scale={61.09} />
    </group>
  )
}

useGLTF.preload('/LOGO.glb')
